#!/usr/bin/env python

import sys
from moosic.client.factory import LocalMoosicProxy
from moosic.utilities import xmlrpc_server_doc

if len(sys.argv) < 2:
    server_proxy = LocalMoosicProxy()
else:
    server_proxy = LocalMoosicProxy(sys.argv[1])

items = xmlrpc_server_doc(server_proxy).items()
items.sort()
print
print '=over'
print
for i in items:
    if not i[0].startswith('_'):
        print i[1], "\n"
print
print '=back'
print
